version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    container_name: flask-backend
    # Flask already has host='0.0.0.0' in app.run()

  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    container_name: express-frontend
    depends_on:
      - backend
